[package]
name = "shift-lib-rs-graph"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
repository = ""
keywords = ["competitive"]
publish = false

[lib]
name = "graph"

[dependencies]
rustc-hash = "=1.1.0"
num-traits = "=0.2.11"
