[package]
name = "shift-lib-rs-swag"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
repository = ""
keywords = ["competitive"]
publish = false

[lib]
name = "swag"

[dependencies]
__traits = { package = "shift-lib-rs-traits", version = "0.1.0", path = "../traits" }
