[package]
name = "shift-lib-rs-data-structure"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
repository = ""
keywords = ["competitive"]
publish = false

[lib]
name = "shift_data_structure"

[dependencies]
alga = "=0.9.3"
__shift_general = { package = "shift-lib-rs-general", version = "0.1.0", path = "/home/shift/rust_lib/general" }
num-traits = "=0.2.11"