[package]
name = "shift-lib-rs-dynamic-segtree"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
repository = ""
keywords = ["competitive"]
publish = false

[lib]
name = "dynamic_segtree"

[dependencies]
__traits = { package = "shift-lib-rs-traits", version = "0.1.0", path = "../traits" }
