[package]
name = "shift-lib-rs-doubling"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
repository = ""
keywords = ["competitive"]
publish = false

[lib]
name = "shift_doubling"

[dependencies]
__shift_traits = { package = "shift-lib-rs-traits", version = "0.1.0", path = "../traits" }
